### ISSUE TITLE
Fix "Major Bugs" referenced in README

### ISSUE THREAD

**Issue by s-ol** [adrianchifor/TapUnlock#3]
Is there a reason this is no longer in the play store? Does it still work?

**Comment by S0lll0s** [comment]
my god I am blind.

**Comment by adrianchifor** [comment]
They're on the backlog. I didn't have time to work on them these past few months but I will resolve them over the next 2-3 weeks, do a redesign and fresh release. Thanks for reminding me xD

**Comment by ironAss** [comment]
Is this backlog public? If you creates issues rather than keeping the backlog for yourself, we may help you :)
